const hostingPrice = [
  {
    name: 'baby',
    bestSeller: false,
    originalPrice: 20000,
    discountPrice: 12000,
    features: [
      '500MB Penyimpanan',
      '1TB Bandwith',
      '2 Domain',
      'Gratis Keamanan SSL',
      'Unlimited Database',
      'Free Back-up',
    ],
  },
  {
    name: 'personal',
    bestSeller: true,
    originalPrice: 70000,
    discountPrice: 49000,
    features: [
      '7GB Penyimpanan',
      'Unlimited Bandwith',
      '20 Domain',
      'Gratis Keamanan SSL',
      'Unlimited Database',
      'Free Back-up',
      'Free Website Builder',
      'Unlimited Email',
      'Gratis Domain',
    ],
  },
  {
    name: 'organisasi',
    bestSeller: false,
    originalPrice: 98000,
    discountPrice: 70000,
    features: [
      '25GB Penyimpanan',
      'Unlimited Bandwith',
      'Unlimited Domain',
      'Gratis Keamanan SSL',
      'Unlimited Database',
      'Free Back-up',
      'Free Website Builder',
      'Unlimited Email',
      'Gratis Domain',
      'Keamanan Email',
    ],
  },
  {
    name: 'bisnis',
    bestSeller: false,
    originalPrice: 150000,
    discountPrice: 98000,
    features: [
      '100GB Penyimpanan',
      'Unlimited Bandwith',
      'Unlimited Domain',
      'Gratis Keamanan SSL',
      'Unlimited Database',
      'Free Back-up',
      'Free Website Builder',
      'Unlimited Email',
      'Gratis Domain',
      'Keamanan Email',
      'Auto Back-up 24 Jam',
    ],
  },
];

export default hostingPrice;
